# Generated by Django 5.0.6 on 2025-04-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembase',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='itembase',
            name='department_name',
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['site'], 'verbose_name': 'Storage Location'},
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
