# Generated by Django 5.0.1 on 2024-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='critical_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
