# Generated by Django 5.0.6 on 2025-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_itembase_client_name_remove_item_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
