# Generated by Django 5.0.1 on 2024-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itembase_critical_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
