# Generated by Django 5.0.6 on 2025-04-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_department_item_department_itembase_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcode',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
    ]
