# Generated by Django 5.0.6 on 2024-07-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_item_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
