# Generated by Django 5.0.6 on 2024-07-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itembase_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['client']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department']},
        ),
    ]
