# Generated by Django 5.0.6 on 2024-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_client_options_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='middleName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
