# Generated by Django 5.0.6 on 2025-04-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_itemcode_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcode',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
    ]
