# Generated by Django 5.0.6 on 2024-09-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_firstname_item_lastname_item_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='itembase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='itembase',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='itembase',
            name='total_value',
        ),
    ]
