# Generated by Django 5.0.6 on 2024-11-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_item_item_value_remove_item_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Staff Name',
                'ordering': ['member'],
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='middleName',
        ),
        migrations.AddField(
            model_name='item',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.teammember'),
        ),
    ]
