# Generated by Django 5.0.6 on 2025-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_itemcode_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itembase',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
