# Generated by Django 5.0.6 on 2024-11-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_floor_site_itemcode_floor_floor_site_itemcode_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.floor'),
        ),
        migrations.AddField(
            model_name='item',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.site'),
        ),
    ]
