# Generated by Django 5.0.6 on 2024-11-25 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_floor_item_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.client'),
        ),
        migrations.AddField(
            model_name='itembase',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
        migrations.AddField(
            model_name='itembase',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.floor'),
        ),
        migrations.AddField(
            model_name='itembase',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.site'),
        ),
    ]
