# Generated by Django 5.0.6 on 2024-11-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_itembase_client_name_itembase_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembase',
            name='floor',
        ),
    ]
