# Generated by Django 5.0.6 on 2024-11-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_itembase_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='floor',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcode'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
