# Generated by Django 5.0.6 on 2024-11-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_item_floor_alter_item_item_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcode',
            name='floor',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
